version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go test -v ./...

workflows:
  version: 2
  test:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
